#数据库的配置
spring:
  datasource:
    username: root
    password: 8888
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


mybatis:
  type-aliases-package: cn.whut.springboot03
  mapper-locations: classpath:mapper/*.xml
